### ISSUE TITLE
ruby gets requires twice enter input when zxing gem is used

### ISSUE THREAD

**Issue by sachinkale** [ecin/zxing.rb#3]
## Consider this code - 

require 'rubygems'
require 'zxing'

puts "Press enter to continue"
gets
## puts "ok"

I have to enter twice to get to "ok"
## Where else w/o zxing only pressing enter once gets to "ok"

require 'rubygems'

puts "Press enter to continue"
gets
## puts "ok"

Thanks for this gem!
I can live with workaround till it gets fixed.

**Comment by smparkes** [comment]
That's weird ...

**Comment by ecin** [comment]
Which Ruby version are you testing with?

**Comment by sachinkale** [comment]
ruby 1.8.7 (2010-08-16 patchlevel 302) [i686-linux]

**Comment by ecin** [comment]
The offending code is in zxing/server.rb; it starts a separate thread that attempts to read from STDIN as a way of verifying that the parent program is still running. Should be a better way of verifying this.

**Comment by ecin** [comment]
Problem fixed, new gem pushed (v0.3.1)
