### ISSUE TITLE
Issue with Ruby

### ISSUE THREAD

**Issue by dgtm** [ecin/zxing.rb#5]
With the following Gemfile configuration

```
gem 'zxing'
gem "libv8", "~> 3.3.10.4"
```

When I run rails console under Ruby 1.9.2 or 1.9.3, I get the following error

```
Bundler::GemNotFound: Could not find libv8-3.3.10.4 in any of the sources
```

It stems from:

```
      map! at org/jruby/RubyArray.java:2358
```

I have tried two versions of bundler and the Gem is finely listed in both of them.

**Comment by ecin** [comment]
I'll test this out in Ruby 1.9.2/3 and get back to you.

**Comment by patcon** [comment]
I think I had the same issue. It's from vendoring your gems with your project using `bundle install --path=vendor` or something. I removed `.bundle/` and reran 'bundle install` and it seems to be working fine :)
