### ISSUE TITLE
Updated JARs?

### ISSUE THREAD

**Issue by jwoertink** [ecin/zxing.rb#8]
I just tried using this gem, and with a 2D barcode, I keep getting nil, but when I try the same image on http://zxing.org/w/decode.jspx I get the result I'm looking for. My guess is maybe the JARs need to be updated. I went to http://code.google.com/p/zxing/ to try and compile them myself, but I keep getting an error for the javase.jar.

Thoughts?

**Comment by ecin** [comment]
A year later, the JARs have been updated with the `0.4.0` release.
